/* Generated by tools/gen-assets.js. */
(function (root) { (root.NB || (root.NB = {})).ASSET_FILES = {
 "places": {
  "bracken_court": "art/places/bracken-court.png",
  "calder_general": "art/places/calder-general.png",
  "double_shift": "art/places/double-shift.png",
  "iron_footbridge": "art/places/iron-footbridge.png",
  "lyles_bakery": "art/places/lyles-bakery.png",
  "mercy_house": "art/places/mercy-house.png",
  "neutral_table": "art/places/neutral-table.png",
  "northline_station": "art/places/northline-station.png",
  "okafor_restoration": "art/places/okafor-restoration.png",
  "orchard_house": "art/places/orchard-house.png",
  "print_shop": "art/places/print-shop.png",
  "pump_nine": "art/places/pump-nine.png",
  "regent": "art/places/regent.png",
  "rell_company": "art/places/rell-company.png",
  "rusk_funeral": "art/places/rusk-funeral.png",
  "serrano_yard": "art/places/serrano-yard.png",
  "sorrell_house": "art/places/sorrell-house.png",
  "stillwater_docks": "art/places/stillwater-docks.png",
  "switchyard_lane": "art/places/switchyard-lane.png",
  "university": "art/places/university.png"
 },
 "cards": {},
 "portraits": {},
 "snapshots": {}
}; })(typeof window !== "undefined" ? window : globalThis);
