/* Calder — the art bridge. Everything the UI shows comes through here:
 *   NB.cards    places, chapter cards, ending cards (320×180), resolved from NB.ASSET_FILES
 *   NB.portraits  character portraits (128×160), delivered as PNGs by ChatGPT; until a file arrives, a quiet
 *                 placeholder bust in that person's colour stands in, so no scene ever breaks for want of art.
 * NB.ASSET_FILES is generated by tools/gen-assets.js (paths in development, data URIs in the single-file build).
 */
(function (root) {
  "use strict";
  var NB = root.NB || (root.NB = {});
  var P = NB.pixel;
  function files() { return NB.ASSET_FILES || { places: {}, portraits: {}, cards: {}, snapshots: {} }; }

  /* ---------------------------------------------------------------- cards */
  var W = 320, H = 180;
  function cardFile(id) {
    var f = files();
    if (f.cards[id]) return f.cards[id];
    if (f.places[id]) return f.places[id];
    var cfg = NB.config || {};
    var alias = (cfg.cardAliases || {})[id];
    if (alias && alias !== id) return cardFile(alias);
    return null;
  }
  NB.cards = {
    W: W, H: H,
    get ids() { var f = files(), cfg = NB.config || {}; return Object.keys(f.places).concat(Object.keys(f.cards), Object.keys(cfg.cardAliases || {})); },
    url: function (id) { return cardFile(id) || placeholderCard(id); },
    has: function (id) { return !!cardFile(id); }
  };
  var cache = {};
  function placeholderCard(id) {
    if (cache["card:" + id]) return cache["card:" + id];
    if (!P || !P.toDataURL) return "";
    var c = P.canvas(W, H);
    c.vgrad(0, 0, W, H, ["#2a2262", "#1f1a4e", "#16133a"]);
    for (var i = 0; i < 40; i++) c.set((i * 97) % W, (i * 53) % (H / 2), "#d8d0f4");
    return (cache["card:" + id] = P.toDataURL(c, "card:" + id));
  }

  /* ---------------------------------------------------------------- portraits */
  var PW = 128, PH = 160;
  var TONES = ["#5e3f9e", "#285a64", "#9a3a32", "#4a7af0", "#1a9e8e", "#b04a8a", "#e07a30", "#62a8a0"];
  function hashStr(s) { var h = 0; for (var i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0; return Math.abs(h); }
  /* Expressions. Scenes tag lines with a rich set of moods; each falls back through near neighbours to the six
   * baseline expressions, then neutral, so a line always finds the closest face that was actually drawn. Names
   * ChatGPT may have used for the same faces are accepted as synonyms. */
  var MOOD_CHAIN = {
    neutral: ["neutral", "default", "calm", "idle"],
    attentive: ["attentive", "curious", "interested", "listening", "focused", "thinking", "neutral"],
    amused: ["amused", "happy", "smile", "smiling", "laugh", "laughing", "grin", "neutral"],
    laugh: ["laugh", "laughing", "amused", "happy", "smile", "neutral"],
    warm: ["warm", "soft", "fond", "tender", "gentle", "smile", "amused", "neutral"],
    shy: ["shy", "embarrassed", "blush", "blushing", "flustered", "warm", "soft", "neutral"],
    tense: ["tense", "worried", "anxious", "nervous", "serious", "neutral"],
    scared: ["scared", "afraid", "frightened", "shocked", "tense", "worried", "neutral"],
    angry: ["angry", "annoyed", "irritated", "frustrated", "tense", "serious", "neutral"],
    hurt: ["hurt", "sad", "upset", "pained", "tense", "neutral"],
    sad: ["sad", "hurt", "upset", "neutral"],
    guarded: ["guarded", "wary", "cold", "serious", "tense", "neutral"],
    surprised: ["surprised", "shocked", "startled", "attentive", "neutral"],
    tired: ["tired", "exhausted", "weary", "sad", "neutral"],
    moon: ["moon", "wolf", "tense", "neutral"],
    hungry: ["hungry", "tense", "neutral"],
    returned: ["returned", "neutral"],
    small: ["small", "neutral"]
  };
  function chain(mood) { return MOOD_CHAIN[mood] || [mood, "neutral"]; }
  function portraitFile(id, mood, variant) {
    var f = files().portraits, c = chain(mood || "neutral");
    if (variant) {
      for (var i = 0; i < c.length; i++) if (f[id + ":" + variant + "-" + c[i]]) return f[id + ":" + variant + "-" + c[i]];
      if (f[id + ":" + variant]) return f[id + ":" + variant];
    }
    for (var j = 0; j < c.length; j++) if (f[id + ":" + c[j]]) return f[id + ":" + c[j]];
    return null;
  }
  function placeholder(id) {
    var key = "ph:" + id;
    if (cache[key]) return cache[key];
    if (!P || !P.toDataURL) return "";
    var c = P.canvas(PW, PH), tone = TONES[hashStr(id) % TONES.length];
    c.vgrad(0, 0, PW, PH, [P.shade(tone, -0.55), P.shade(tone, -0.75)]);
    var sil = P.shade(tone, -0.35);
    c.ellipse(64, 62, 24, 29, sil);
    c.rect(54, 86, 20, 16, sil);
    c.poly([[10, 160], [22, 112], [48, 100], [80, 100], [106, 112], [118, 160]], sil);
    return (cache[key] = P.toDataURL(c, key));
  }
  NB.portraits = {
    W: PW, H: PH,
    moods: Object.keys(MOOD_CHAIN),
    has: function (id, mood, variant) { return !!portraitFile(id, mood || "neutral", variant); },
    url: function (id, mood, variant) { return portraitFile(id, mood || "neutral", variant) || placeholder(id); },
    faceUrl: function (id, mood, variant) { var f = files().portraits; return (!variant && mood === "neutral" && f[id + ":small"]) || portraitFile(id, mood || "neutral", variant) || placeholder(id); },
    lookOptions: {}, lookLabels: {}
  };

  /* ---------------------------------------------------------------- snapshots */
  NB.snapshots = {
    has: function (id) { return !!files().snapshots[id]; },
    url: function (id) {
      var f = files().snapshots[id];
      if (f) return f;
      var cfg = NB.config || {}, s = (cfg.snapshots || {})[id];
      return s && s.bg ? NB.cards.url(s.bg) : placeholderCard(id);
    }
  };
})(typeof window !== "undefined" ? window : globalThis);
