/* Calder — generated by tools/gen-config.js from plan/. Do not edit by hand. */
(function (root) {
  "use strict";
  var NB = root.NB || (root.NB = {});
  NB.plan = {
 "startVars": {
  "name": "Theo",
  "steam": true,
  "date": "2026-08-29",
  "ch": 1,
  "nerve": 20,
  "craft": 30,
  "people": 20,
  "knack": 10,
  "strain": 0,
  "reached": 0,
  "gift_named": false,
  "trained": "none",
  "gift_adrian": false,
  "gift_micah": false,
  "gift_ellis": false,
  "gift_dominic": false,
  "gift_nolan": false,
  "gift_ansel": false,
  "gift_quentin": false,
  "gift_reuben": false,
  "gift_martin": false,
  "gift_mercy": false,
  "gift_damian": false,
  "know_super": false,
  "know_wardens": false,
  "know_vampires": false,
  "know_wolves": false,
  "know_spell": false,
  "know_marches": false,
  "know_micah_wolf": false,
  "know_dominic_vamp": false,
  "know_damian": false,
  "know_deadline": false,
  "know_donors": 0,
  "know_clive_taken": false,
  "e01": false,
  "e01_src": "",
  "e01_c": false,
  "e02": false,
  "e02_src": "",
  "e02_c": false,
  "e03": false,
  "e03_src": "",
  "e03_c": false,
  "e04": false,
  "e04_src": "",
  "e04_c": false,
  "e05": false,
  "e05_src": "",
  "e05_c": false,
  "e06": false,
  "e06_src": "",
  "e06_c": false,
  "e07": false,
  "e07_src": "",
  "e07_c": false,
  "e08": false,
  "e08_src": "",
  "e08_c": false,
  "e09": false,
  "e09_src": "",
  "e09_c": false,
  "e10": false,
  "e10_src": "",
  "e10_c": false,
  "e11": false,
  "e11_src": "",
  "e11_c": false,
  "e12": false,
  "e12_src": "",
  "e12_c": false,
  "e13": false,
  "e13_src": "",
  "e13_c": false,
  "e14": false,
  "e14_src": "",
  "e14_c": false,
  "e15": false,
  "e15_src": "",
  "e15_c": false,
  "e16": false,
  "e16_src": "",
  "e16_c": false,
  "e17": false,
  "e17_src": "",
  "e17_c": false,
  "e18": false,
  "e18_src": "",
  "e18_c": false,
  "told_gareth": false,
  "told_mercy": false,
  "told_regent": false,
  "told_eastbank": false,
  "st_adrian": 0,
  "hurt_adrian": 0,
  "closed_adrian": false,
  "out_adrian": false,
  "st_micah": 0,
  "hurt_micah": 0,
  "closed_micah": false,
  "out_micah": false,
  "st_ellis": 0,
  "hurt_ellis": 0,
  "closed_ellis": false,
  "out_ellis": false,
  "st_dominic": 0,
  "hurt_dominic": 0,
  "closed_dominic": false,
  "out_dominic": false,
  "st_nolan": 0,
  "hurt_nolan": 0,
  "closed_nolan": false,
  "out_nolan": false,
  "st_ansel": 0,
  "hurt_ansel": 0,
  "closed_ansel": false,
  "out_ansel": false,
  "st_quentin": 0,
  "hurt_quentin": 0,
  "closed_quentin": false,
  "out_quentin": false,
  "st_reuben": 0,
  "hurt_reuben": 0,
  "closed_reuben": false,
  "out_reuben": false,
  "fr_martin": 0,
  "fr_will": 0,
  "fr_gideon": 0,
  "fr_florian": 0,
  "fr_malcolm": 0,
  "fr_chukwudi": 0,
  "fr_otis": 0,
  "fr_silas": 0,
  "fr_felix": 0,
  "fr_desmond": 0,
  "fr_peter": 0,
  "fr_owen": 0,
  "fr_pavel": 0,
  "fr_ernesto": 0,
  "fr_leandro": 0,
  "fr_wesley": 0,
  "fr_lucien": 0,
  "fr_rafi": 0,
  "fr_milo": 0,
  "fr_benoit": 0,
  "fr_graham": 0,
  "fr_victor": 0,
  "fr_darius": 0,
  "fr_emmett": 0,
  "fr_kenji": 0,
  "fr_nabil": 0,
  "fr_ilyas": 0,
  "fr_gareth": 0,
  "fr_russell": 0,
  "fr_sylvester": 0,
  "fr_harlan": 0,
  "fr_lucan": 0,
  "fr_percival": 0,
  "fr_severin": 0,
  "fr_eamon": 0,
  "fr_hugo": 0,
  "fr_clive": 0,
  "fr_isaac": 0,
  "fr_caspar": 0,
  "fr_jonah": 0,
  "look_done": false,
  "ch01_saw": "",
  "hurt_mc": 0,
  "echo_lane": false,
  "letters_mum": 0,
  "eamon_heard": false,
  "clinic_lead": false,
  "button_shown": false,
  "misread_gideon": false,
  "suspect_gideon": false,
  "theory": "",
  "course_lead": false,
  "error_book": false,
  "managed_dominic": false,
  "gareth_wary": false,
  "harlan_aware": false,
  "good_coat": false,
  "micah_deflects": false,
  "same_voice": false,
  "lease_mark": false,
  "suspect_donor": false,
  "savings_given": false,
  "shop_hours": false,
  "hugo_met": false,
  "nolan_applied": false,
  "tomas_injury": false,
  "silas_trusts": false,
  "silas_protected": false,
  "repeated": false,
  "buddy_plan": false,
  "hugo_missing": false,
  "same_voice2": false,
  "gareth_hugo": false,
  "mimic_words": false,
  "old_map": false,
  "mimic_clue": false,
  "adrian_plan": false,
  "tunnels_role": "",
  "tunnels_done": false,
  "shade_lonely": false,
  "screen_panel": false,
  "screen_way": "",
  "screen_done": false,
  "program_hint": false,
  "adrian_asks_emmett": false,
  "carrow_file": false,
  "orrell_suspected": false,
  "damian_named": false,
  "damian_program": false,
  "crossings_map": false,
  "ex_as": "",
  "armand_met": false,
  "august_watched": false,
  "octavian_known": false,
  "armand_hope": false,
  "armand_hint": false,
  "armand_trust": false,
  "e11_copy": false,
  "warned_felix": false,
  "frame_seen": false,
  "rell_lead": false,
  "frame_echo": false,
  "ellis_fights": false,
  "nolan_knows": false,
  "wesley_saved": "",
  "ally_regent_hint": false,
  "crew_paid": false,
  "haunting_done": false,
  "voice_heard": false,
  "winton_log": false,
  "russell_logging": false,
  "martin_told_trip": false,
  "harlan_nervous": false,
  "oswin_met": false,
  "registry_access": false,
  "oswin_wary": false,
  "eamon_bag": false,
  "eamon_letter_kept": false,
  "eamon_hope": false,
  "still_lead": "",
  "ansel_spoke": false,
  "threads_three": false,
  "saw_crew": false,
  "boat_photo": false,
  "shift_change": false,
  "witness_safe": false,
  "inside_man": false,
  "eamon_saw": false,
  "still_layout": false,
  "felix_returned": false,
  "pump_film": false,
  "felix_shared": false,
  "felix_told": false,
  "patients_matched": false,
  "patients_asked": false,
  "simeon_pressed": false,
  "course_confirms": false,
  "wk16": "",
  "adrian_later": false,
  "friends_ch17": false,
  "out_family": false,
  "family_case": false,
  "slow_ch17": false,
  "coalition_seat": "",
  "options_known": false,
  "mat_frame": false,
  "mat_stones": false,
  "mat_thread": false,
  "owe_august": false,
  "ansel_defied": false,
  "mc_volunteered": false,
  "orrell_pressed": false,
  "orrell_deal": false,
  "q_free_first": false,
  "harlan_hostile": false,
  "knack_monitor": false,
  "summoned": false,
  "armand_broken": false,
  "armand_hard": false,
  "plan_chosen": "",
  "last_with": "",
  "cap": 0,
  "cap_full": false,
  "cap_interim": false,
  "cap_pair": false,
  "monitor": "",
  "reuben_faced": false,
  "mum_told": false,
  "out_mum": false,
  "nolan_leaving": false,
  "ellis_leaving": false,
  "adrian_transfer": false,
  "micah_away": false,
  "dominic_away": false,
  "quentin_away": false,
  "reuben_away": false,
  "cuff_button": false,
  "enemy_aware": 0,
  "ch02_report": "",
  "ch03_way": "",
  "ch04_first": "",
  "ch05_route": "",
  "ch06_way": "",
  "ch07_evening": "",
  "ch07_late": false,
  "ch08_way": "",
  "ch09_case": "",
  "ch10_way": "",
  "orrell_known": "",
  "ch11_talk": "",
  "ch12_branch": "",
  "companion": "none",
  "ch13_lodging": "",
  "ch14_way": "",
  "ch15_way": "",
  "ch17_ask": "",
  "ch19_answer": "",
  "role": "",
  "s01": "",
  "s02": "",
  "s03": "",
  "s04": "",
  "s05": "",
  "s06": "",
  "s07": "",
  "s08": "",
  "s09": "",
  "s10": "",
  "s11": "",
  "s12": "",
  "s13": "",
  "s14": "",
  "s15": "",
  "s16": "",
  "plan_full": false,
  "plan_interim": false,
  "plan_pair": false,
  "materials": 0,
  "volunteers": 0,
  "consent_q": false,
  "consent_s": false,
  "consent_f": false,
  "ally_mercy": false,
  "ally_eastbank": false,
  "ally_regent": false,
  "ally_circle": false,
  "ally_keepers": false,
  "ally_court": false,
  "acc_pump": false,
  "acc_still": false,
  "acc_cross": false,
  "harlan_confessed": false,
  "ending": "",
  "alive_quentin": true,
  "alive_silas": true,
  "alive_felix": true,
  "donors_freed": false,
  "damian_fate": "",
  "armand_fate": "",
  "august_fate": "",
  "orrell_fate": "",
  "disclosure": "",
  "final_rel": "",
  "final_shape": "",
  "mc_future": ""
 },
 "clamp": {
  "nerve": [
   0,
   100
  ],
  "craft": [
   0,
   100
  ],
  "people": [
   0,
   100
  ],
  "knack": [
   0,
   100
  ],
  "strain": [
   0,
   3
  ],
  "st_adrian": [
   0,
   6
  ],
  "hurt_adrian": [
   0,
   2
  ],
  "st_micah": [
   0,
   6
  ],
  "hurt_micah": [
   0,
   2
  ],
  "st_ellis": [
   0,
   6
  ],
  "hurt_ellis": [
   0,
   2
  ],
  "st_dominic": [
   0,
   6
  ],
  "hurt_dominic": [
   0,
   2
  ],
  "st_nolan": [
   0,
   6
  ],
  "hurt_nolan": [
   0,
   2
  ],
  "st_ansel": [
   0,
   6
  ],
  "hurt_ansel": [
   0,
   2
  ],
  "st_quentin": [
   0,
   6
  ],
  "hurt_quentin": [
   0,
   2
  ],
  "st_reuben": [
   0,
   6
  ],
  "hurt_reuben": [
   0,
   2
  ],
  "fr_martin": [
   0,
   3
  ],
  "fr_will": [
   0,
   3
  ],
  "fr_gideon": [
   0,
   3
  ],
  "fr_florian": [
   0,
   3
  ],
  "fr_malcolm": [
   0,
   3
  ],
  "fr_chukwudi": [
   0,
   3
  ],
  "fr_otis": [
   0,
   3
  ],
  "fr_silas": [
   0,
   3
  ],
  "fr_felix": [
   0,
   3
  ],
  "fr_desmond": [
   0,
   3
  ],
  "fr_peter": [
   0,
   3
  ],
  "fr_owen": [
   0,
   3
  ],
  "fr_pavel": [
   0,
   3
  ],
  "fr_ernesto": [
   0,
   3
  ],
  "fr_leandro": [
   0,
   3
  ],
  "fr_wesley": [
   0,
   3
  ],
  "fr_lucien": [
   0,
   3
  ],
  "fr_rafi": [
   0,
   3
  ],
  "fr_milo": [
   0,
   3
  ],
  "fr_benoit": [
   0,
   3
  ],
  "fr_graham": [
   0,
   3
  ],
  "fr_victor": [
   0,
   3
  ],
  "fr_darius": [
   0,
   3
  ],
  "fr_emmett": [
   0,
   3
  ],
  "fr_kenji": [
   0,
   3
  ],
  "fr_nabil": [
   0,
   3
  ],
  "fr_ilyas": [
   0,
   3
  ],
  "fr_gareth": [
   0,
   3
  ],
  "fr_russell": [
   0,
   3
  ],
  "fr_sylvester": [
   0,
   3
  ],
  "fr_harlan": [
   0,
   3
  ],
  "fr_lucan": [
   0,
   3
  ],
  "fr_percival": [
   0,
   3
  ],
  "fr_severin": [
   0,
   3
  ],
  "fr_eamon": [
   0,
   3
  ],
  "fr_hugo": [
   0,
   3
  ],
  "fr_clive": [
   0,
   3
  ],
  "fr_isaac": [
   0,
   3
  ],
  "fr_caspar": [
   0,
   3
  ],
  "fr_jonah": [
   0,
   3
  ],
  "hurt_mc": [
   0,
   2
  ]
 },
 "leads": [
  "adrian",
  "micah",
  "ellis",
  "dominic",
  "nolan",
  "ansel",
  "quentin",
  "reuben"
 ],
 "people": {
  "mc": {
   "cid": "MC",
   "name": "Theo Marsh",
   "age": 19,
   "kind": "human",
   "tier": "lead",
   "romance": false,
   "appearance": "Chosen by the player: skin tone, hair colour and style, facial hair, eyes. Never shown in snapshots.",
   "status": [],
   "home": "P02"
  },
  "adrian": {
   "cid": "C01",
   "name": "Adrian Keene",
   "age": 20,
   "kind": "warden",
   "tier": "lead",
   "romance": true,
   "appearance": "Compact rectangular face, firm rounded jaw, straight brows (left a touch higher), sturdy neck. Short close brown curls, medium olive skin. High-collared practical jacket with replaced elastic cuffs.",
   "status": [],
   "home": "P01"
  },
  "micah": {
   "cid": "C02",
   "name": "Micah Serrano",
   "age": 21,
   "kind": "wolf",
   "tier": "lead",
   "romance": true,
   "appearance": "Broad cheekbones and nose, fuller lower face, thick neck, wide shoulders. Dark wavy hair, untidy at the front; warm tan skin; wide mouth with an uneven smile. Work jacket with a pencil in the pocket.",
   "status": [],
   "home": "P07"
  },
  "ellis": {
   "cid": "C03",
   "name": "Ellis Okafor",
   "age": 20,
   "kind": "spell",
   "tier": "lead",
   "romance": true,
   "appearance": "Long fine-boned face, distinct cheek planes, narrow neck, expressive brows. Dense dark coils kept off the face; deep brown skin; defined mouth. Careful, cheap, well-kept clothes; a much-mended bag.",
   "status": [],
   "home": "P20"
  },
  "dominic": {
   "cid": "C04",
   "name": "Dominic Bell",
   "age": 22,
   "kind": "vampire",
   "tier": "lead",
   "romance": true,
   "appearance": "Square-oval face, soft cheeks, substantial nose, solid build. Thick dark hair falling forward; warm natural complexion kept after turning; old knitwear.",
   "status": [],
   "home": "P14"
  },
  "nolan": {
   "cid": "C05",
   "name": "Nolan Voss",
   "age": 19,
   "kind": "human",
   "tier": "lead",
   "romance": true,
   "appearance": "Long oval face, softer cheeks, slightly prominent ears, loose posture, long legs and a softer middle. Sandy hair with an uneven fringe, light freckled skin. Plain work shirt; always turning something over in his hands.",
   "status": [],
   "home": "P28"
  },
  "ansel": {
   "cid": "C06",
   "name": "Ansel Marr",
   "age": 21,
   "kind": "marches",
   "tier": "lead",
   "romance": true,
   "appearance": "Tapered face, clear cheekbones, longer nose, measured posture. Smooth dark hair with a controlled side part, cool light skin. A formal collar even for chips.",
   "status": [],
   "home": "P55"
  },
  "quentin": {
   "cid": "C07",
   "name": "Quentin Shaw",
   "age": 22,
   "kind": "human",
   "tier": "lead",
   "romance": true,
   "appearance": "Broad, shorter face; strong brows; compact solid build, strong forearms. Close dark curls, deep warm-brown skin, a direct gaze and a mobile mouth.",
   "status": [
    {
     "date": "2026-08-30",
     "state": "dead",
     "note": "00:40, Switchyard rear lane"
    },
    {
     "date": "2026-08-30",
     "state": "returned",
     "note": "linked to Eamon"
    }
   ],
   "home": "P43"
  },
  "reuben": {
   "cid": "C08",
   "name": "Reuben Pike",
   "age": 23,
   "kind": "warden",
   "tier": "lead",
   "romance": true,
   "appearance": "Broad long face, heavier lower jaw, big neck and shoulders. Short wavy chestnut hair he cuts himself, light-brown skin, low-set brows, mild tiredness under the eyes.",
   "status": [],
   "home": "P01"
  },
  "will": {
   "cid": "C09",
   "name": "Will Avery",
   "age": 17,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Tall for his age, all elbows; light brown skin from his mother's side (she lives in the south with her new family), cropped black hair, a school team hoodie.",
   "status": [],
   "home": "P02"
  },
  "martin": {
   "cid": "C10",
   "name": "Martin Avery",
   "age": 44,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Heavyset, soft-spoken face, reading glasses pushed up into thinning sandy-grey hair, ink on his fingers, fair skin reddened by the press room heat.",
   "status": [],
   "home": "P02"
  },
  "peter": {
   "cid": "C11",
   "name": "Peter Laird",
   "age": 20,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Neat, narrow face, gelled brown hair, pale skin, a lanyard he treats like a badge of office.",
   "status": [],
   "home": "P28"
  },
  "owen": {
   "cid": "C12",
   "name": "Owen Price",
   "age": 26,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Long patient face, black skin, short twists, a driver's fleece with the union pin on it.",
   "status": [],
   "home": "P28"
  },
  "nabil": {
   "cid": "C13",
   "name": "Nabil Haddad",
   "age": 21,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Round face, olive skin, thick black brows, neat short beard following the jaw, glasses; hospital reception lanyard.",
   "status": [],
   "home": "P21"
  },
  "russell": {
   "cid": "C14",
   "name": "Russell Dacre",
   "age": 58,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Weathered long face, white stubble kept short, fair skin, a flat cap and a tool belt; moves carefully on a bad knee.",
   "status": [],
   "home": "P41"
  },
  "benoit": {
   "cid": "C15",
   "name": "Benoît Marchand",
   "age": 31,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Lively narrow face, dark hair swept back, light olive skin, a scarf worn indoors, pencil behind the ear.",
   "status": [],
   "home": "P34"
  },
  "gareth": {
   "cid": "C16",
   "name": "Gareth Moss",
   "age": 33,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Square pale face, ginger hair cut short, rain jacket, a notebook he actually uses.",
   "status": [],
   "home": "P43"
  },
  "victor": {
   "cid": "C17",
   "name": "Victor Keene",
   "age": 27,
   "kind": "warden",
   "tier": "frequent",
   "romance": false,
   "appearance": "Adrian's face grown longer and more tired; same brown curls, olive skin; a brace on the left forearm; charming when he's performing.",
   "status": [],
   "home": "P01"
  },
  "orrell": {
   "cid": "C18",
   "name": "Patrick Orrell",
   "age": 54,
   "kind": "warden",
   "tier": "frequent",
   "romance": false,
   "appearance": "Grey crew cut, heavy brow, pale lined skin, a commander's stillness; reading glasses he never uses in public.",
   "status": [],
   "home": "P01"
  },
  "simeon": {
   "cid": "C19",
   "name": "Simeon Rusk",
   "age": 46,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Gentle round face, balding, dark-brown skin, immaculate black suit, a funeral director's quiet hands.",
   "status": [],
   "home": "P30"
  },
  "darius": {
   "cid": "C20",
   "name": "Darius Chen",
   "age": 24,
   "kind": "warden",
   "tier": "frequent",
   "romance": false,
   "appearance": "Angular face, East Asian features, black hair shaved at the sides, a scar through one brow from training, restless.",
   "status": [],
   "home": "P01"
  },
  "emmett": {
   "cid": "C21",
   "name": "Emmett Hsu",
   "age": 19,
   "kind": "warden",
   "tier": "supporting",
   "romance": false,
   "appearance": "Slight, soft round face, East Asian features, black hair in his eyes, a museum-security polo under a warden jacket.",
   "status": [],
   "home": "P01"
  },
  "florian": {
   "cid": "C22",
   "name": "Florian Adebayo",
   "age": 39,
   "kind": "warden",
   "tier": "supporting",
   "romance": false,
   "appearance": "Long elegant face, dark-brown skin, shaved head, round wire glasses, cardigan with archive gloves in the pocket.",
   "status": [],
   "home": "P01"
  },
  "kenji": {
   "cid": "C23",
   "name": "Kenji Sato",
   "age": 47,
   "kind": "warden",
   "tier": "supporting",
   "romance": false,
   "appearance": "Broad weathered face, greying black hair tied back, East Asian features, burn-scarred forearms, a workshop apron.",
   "status": [],
   "home": "P01"
  },
  "malcolm": {
   "cid": "C24",
   "name": "Malcolm Tait",
   "age": 52,
   "kind": "warden",
   "tier": "frequent",
   "romance": false,
   "appearance": "Rugged face, grey beard kept close to the jaw, ruddy fair skin, wool jumper with holes at the elbows; a dog at his heel.",
   "status": [],
   "home": "P51"
  },
  "ernesto": {
   "cid": "C25",
   "name": "Ernesto Serrano",
   "age": 49,
   "kind": "wolf",
   "tier": "frequent",
   "romance": false,
   "appearance": "Big square face like Micah's, grey at the temples, tan skin, thick moustache, builder's hands.",
   "status": [],
   "home": "P07"
  },
  "leandro": {
   "cid": "C26",
   "name": "Leandro Serrano",
   "age": 25,
   "kind": "wolf",
   "tier": "supporting",
   "romance": false,
   "appearance": "Micah's build gone leaner, dark hair cut close, tan skin, a boxer's flattened nose.",
   "status": [],
   "home": "P07"
  },
  "tomas": {
   "cid": "C27",
   "name": "Tomas Rivas",
   "age": 22,
   "kind": "wolf",
   "tier": "supporting",
   "romance": false,
   "appearance": "Wiry, sharp face, light-brown skin, dark hair in a short ponytail, taped knuckles.",
   "status": [],
   "home": "P11"
  },
  "pavel": {
   "cid": "C28",
   "name": "Pavel Kolar",
   "age": 42,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Long face, fair skin, brown beard trimmed short along the jaw, mechanic's overalls, few words.",
   "status": [],
   "home": "P11"
  },
  "wesley": {
   "cid": "C29",
   "name": "Wesley Dent",
   "age": 19,
   "kind": "wolf",
   "tier": "supporting",
   "romance": false,
   "appearance": "Thin, guarded face, pale skin, shaved head growing out, a hoodie too light for the weather.",
   "status": [],
   "home": "P11"
  },
  "otis": {
   "cid": "C30",
   "name": "Otis Lyle",
   "age": 61,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Round face, pale skin with flour in the creases, white hair, big forearms, apron always on.",
   "status": [],
   "home": "P09"
  },
  "lucien": {
   "cid": "C31",
   "name": "Lucien Arnaud",
   "age": 83,
   "kind": "vampire",
   "tier": "frequent",
   "romance": false,
   "appearance": "Looks thirty-six: fine bones, dark eyes, light olive skin, silver-threaded dark hair he has chosen to keep, a 1970s cardigan.",
   "status": [],
   "home": "P14"
  },
  "gideon": {
   "cid": "C32",
   "name": "Gideon Shaw",
   "age": 29,
   "kind": "vampire",
   "tier": "frequent",
   "romance": false,
   "appearance": "Quentin's face made harder: same brows, deep warm-brown skin, close-cropped hair, a long coat; says things like instructions.",
   "status": [],
   "home": "P14"
  },
  "rafi": {
   "cid": "C33",
   "name": "Rafi Bensaïd",
   "age": 24,
   "kind": "vampire",
   "tier": "frequent",
   "romance": false,
   "appearance": "Quick, mobile face, light-brown skin, curly black hair, nurse's scrubs under a parka.",
   "status": [],
   "home": "P14"
  },
  "sylvester": {
   "cid": "C34",
   "name": "Sylvester Page",
   "age": 48,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Tall, thin, dry face, dark-brown skin, grey goatee, reading glasses on a cord, a good tired suit.",
   "status": [],
   "home": "P36"
  },
  "milo": {
   "cid": "C35",
   "name": "Milo Finch",
   "age": 20,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Small, bright face, pale freckled skin, mop of red-brown hair, a camera always on a strap.",
   "status": [],
   "home": "P14"
  },
  "abel": {
   "cid": "C36",
   "name": "Abel Mercer",
   "age": 57,
   "kind": "vampire",
   "tier": "supporting",
   "romance": false,
   "appearance": "Heavy handsome face going soft, fair skin gone pale, silver hair expensively cut, cashmere.",
   "status": [],
   "home": "P14"
  },
  "chukwudi": {
   "cid": "C37",
   "name": "Chukwudi Okafor",
   "age": 50,
   "kind": "spell",
   "tier": "frequent",
   "romance": false,
   "appearance": "Ellis's long face gone broad and grave, deep brown skin, short grey beard shaped to the jaw, magnifier on a chain.",
   "status": [],
   "home": "P20"
  },
  "isaac": {
   "cid": "C38",
   "name": "Isaac Okafor",
   "age": 16,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Round face, deep brown skin, short hair, safety goggles pushed up on his forehead.",
   "status": [],
   "home": "P20"
  },
  "august": {
   "cid": "C39",
   "name": "August Rell",
   "age": 64,
   "kind": "spell",
   "tier": "supporting",
   "romance": false,
   "appearance": "Soft attentive face, pale skin, white hair worn long and combed back, rings, a velvet waistcoat.",
   "status": [],
   "home": "P31"
  },
  "caspar": {
   "cid": "C40",
   "name": "Caspar Neri",
   "age": 23,
   "kind": "spell",
   "tier": "supporting",
   "romance": false,
   "appearance": "Animated face, olive skin, dark curly hair under a beanie, gaffer tape on his jeans.",
   "status": [],
   "home": "P21"
  },
  "basil": {
   "cid": "C41",
   "name": "Basil Duret",
   "age": 45,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Handsome going to seed, fair skin, floppy grey-blond hair, corduroy jacket, a lecturer's voice.",
   "status": [],
   "home": "P19"
  },
  "ilyas": {
   "cid": "C42",
   "name": "Ilyas Qureshi",
   "age": 28,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Thin intense face, brown skin, short black beard neatly edged, lab coat, pen clicked when thinking.",
   "status": [],
   "home": "P21"
  },
  "jonah": {
   "cid": "C43",
   "name": "Jonah Peake",
   "age": 34,
   "kind": "spell",
   "tier": "supporting",
   "romance": false,
   "appearance": "Gaunt kind face, pale skin, long dark hair tied back, black suit for funerals, a violin case.",
   "status": [],
   "home": "P30"
  },
  "armand": {
   "cid": "C44",
   "name": "Armand Sorrell",
   "age": 56,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Fine-featured, grey-eyed, fair skin, silver hair, bespoke coat; listens with his whole face.",
   "status": [],
   "home": "P37"
  },
  "severin": {
   "cid": "C45",
   "name": "Severin Marr",
   "age": 48,
   "kind": "marches",
   "tier": "frequent",
   "romance": false,
   "appearance": "Ansel's face made severe: long nose, cool pale skin, dark hair silvering, a high formal collar and rings of office.",
   "status": [],
   "home": "P55"
  },
  "harlan": {
   "cid": "C46",
   "name": "Harlan Greaves",
   "age": 35,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Sociable lined face, tanned fair skin, sandy stubble, a keeper's heavy key ring.",
   "status": [],
   "home": "P33"
  },
  "lucan": {
   "cid": "C47",
   "name": "Lucan Verre",
   "age": 26,
   "kind": "marches",
   "tier": "supporting",
   "romance": false,
   "appearance": "Laughing face, freckled light-brown skin, auburn hair worn long, an estate manager's worn good boots.",
   "status": [],
   "home": "P57"
  },
  "percival": {
   "cid": "C48",
   "name": "Percival Tern",
   "age": 73,
   "kind": "marches",
   "tier": "supporting",
   "romance": false,
   "appearance": "Deeply lined brown face, white beard, a ranger's cloak, walks with a staff he doesn't need.",
   "status": [],
   "home": "P60"
  },
  "eamon": {
   "cid": "C49",
   "name": "Eamon Kerr",
   "age": 24,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Lean face, fair skin, black hair, courier's windburn; later hollow-cheeked.",
   "status": [
    {
     "date": "2026-08-28",
     "state": "held",
     "note": "Stillwater, donor to Quentin"
    },
    {
     "date": "2027-03-14",
     "state": "freed",
     "note": "every ending frees the donors"
    }
   ],
   "home": "P33"
  },
  "oswin": {
   "cid": "C50",
   "name": "Oswin Deller",
   "age": 42,
   "kind": "marches",
   "tier": "supporting",
   "romance": false,
   "appearance": "Heavy, pleasant face, ruddy skin, thinning brown hair oiled flat, a merchant's heavy coat.",
   "status": [],
   "home": "P56"
  },
  "silas": {
   "cid": "C51",
   "name": "Silas Fenwick",
   "age": 23,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Soft-featured, pale skin, light brown hair under a baker's cap, watchful eyes.",
   "status": [
    {
     "date": "2026-10-13",
     "state": "dead"
    },
    {
     "date": "2026-10-14",
     "state": "returned",
     "note": "linked to Hugo"
    }
   ],
   "home": "P09"
  },
  "felix": {
   "cid": "C52",
   "name": "Felix Brecht",
   "age": 21,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Sharp, expressive face, fair skin, bleached hair with dark roots, a camera rig and fingerless gloves.",
   "status": [
    {
     "date": "2027-01-02",
     "state": "dead"
    },
    {
     "date": "2027-01-03",
     "state": "returned",
     "note": "linked to Clive"
    }
   ],
   "home": "P21"
  },
  "graham": {
   "cid": "C53",
   "name": "Graham Bell",
   "age": 46,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Dominic's nose and build, fair ruddy skin, thinning dark hair, a caretaker's blue coat and a big key ring.",
   "status": [],
   "home": "P10"
  },
  "desmond": {
   "cid": "C54",
   "name": "Desmond Aster",
   "age": 33,
   "kind": "human",
   "tier": "frequent",
   "romance": false,
   "appearance": "Charming mobile face, black skin, short locs, band T-shirt under a blazer.",
   "status": [],
   "home": "P13"
  },
  "soren": {
   "cid": "C55",
   "name": "Soren Venn",
   "age": 41,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Smooth pale face, precise blond hair, rimless glasses, a developer's quarter-zip.",
   "status": [],
   "home": "P37"
  },
  "damian": {
   "cid": "C56",
   "name": "Damian Holt",
   "age": 38,
   "kind": "warden",
   "tier": "frequent",
   "romance": false,
   "appearance": "Pleasant, attentive face, light-brown skin, dark hair greying early, clean-shaven, a good plain coat. Nothing about him says murderer.",
   "status": [],
   "home": "P16"
  },
  "hugo": {
   "cid": "C57",
   "name": "Hugo Naranjo",
   "age": 28,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Broad friendly face, tan skin, black hair, a depot hi-vis vest; later hollow.",
   "status": [
    {
     "date": "2026-10-12",
     "state": "held",
     "note": "Stillwater, donor to Silas"
    },
    {
     "date": "2027-03-14",
     "state": "freed"
    }
   ],
   "home": "P43"
  },
  "clive": {
   "cid": "C58",
   "name": "Clive Merritt",
   "age": 30,
   "kind": "human",
   "tier": "supporting",
   "romance": false,
   "appearance": "Big, cheerful face, dark-brown skin, clay on his hands, a flat cap; later drawn.",
   "status": [
    {
     "date": "2027-01-01",
     "state": "held",
     "note": "Stillwater, donor to Felix"
    },
    {
     "date": "2027-03-14",
     "state": "freed"
    }
   ],
   "home": "P34"
  }
 },
 "places": {
  "P01": {
   "name": "Mercy House",
   "district": "Old Ward"
  },
  "P02": {
   "name": "Latch Lane print shop and upstairs home",
   "district": "Old Ward"
  },
  "P03": {
   "name": "Calder Library and public records rooms",
   "district": "Old Ward"
  },
  "P04": {
   "name": "St. Brendan's Square",
   "district": "Old Ward"
  },
  "P05": {
   "name": "Old Baths",
   "district": "Old Ward"
  },
  "P06": {
   "name": "Riverside Steps",
   "district": "Old Ward"
  },
  "P07": {
   "name": "Serrano Yard",
   "district": "Eastbank"
  },
  "P08": {
   "name": "Eastbank Boxing Club",
   "district": "Eastbank"
  },
  "P09": {
   "name": "Lyle's Bakery",
   "district": "Eastbank"
  },
  "P10": {
   "name": "Hartley School and shared playing fields",
   "district": "Eastbank"
  },
  "P11": {
   "name": "Lock Street Flats",
   "district": "Eastbank"
  },
  "P12": {
   "name": "Eastbank Allotments",
   "district": "Eastbank"
  },
  "P13": {
   "name": "Switchyard",
   "district": "Foundry Reach"
  },
  "P14": {
   "name": "The Regent",
   "district": "Foundry Reach"
  },
  "P15": {
   "name": "Iron Footbridge",
   "district": "Foundry Reach"
  },
  "P16": {
   "name": "Pump Nine",
   "district": "Foundry Reach"
  },
  "P17": {
   "name": "Freight Market",
   "district": "Foundry Reach"
  },
  "P18": {
   "name": "Truss Road Diner",
   "district": "Foundry Reach"
  },
  "P19": {
   "name": "University arts buildings",
   "district": "University Hill"
  },
  "P20": {
   "name": "Okafor Restoration",
   "district": "University Hill"
  },
  "P21": {
   "name": "Bellweather Court",
   "district": "University Hill"
  },
  "P22": {
   "name": "Whitcomb Museum",
   "district": "University Hill"
  },
  "P23": {
   "name": "Calder General",
   "district": "University Hill"
  },
  "P24": {
   "name": "Observatory Hill Park",
   "district": "University Hill"
  },
  "P25": {
   "name": "Northline Station",
   "district": "Northline"
  },
  "P26": {
   "name": "Double Shift Café",
   "district": "Northline"
  },
  "P27": {
   "name": "Night Bus Depot",
   "district": "Northline"
  },
  "P28": {
   "name": "Laird's Flatshare",
   "district": "Northline"
  },
  "P29": {
   "name": "Sable Records",
   "district": "Northline"
  },
  "P30": {
   "name": "Rusk Funeral Rooms",
   "district": "Northline"
  },
  "P31": {
   "name": "Rell & Company",
   "district": "Market Crescent"
  },
  "P32": {
   "name": "Crescent Market",
   "district": "Market Crescent"
  },
  "P33": {
   "name": "Little Glass Arcade",
   "district": "Market Crescent"
  },
  "P34": {
   "name": "The Lantern Rooms",
   "district": "Market Crescent"
  },
  "P35": {
   "name": "The Neutral Table",
   "district": "Market Crescent"
  },
  "P36": {
   "name": "Calder Tenants' Advice Centre",
   "district": "Market Crescent"
  },
  "P37": {
   "name": "Sorrell House",
   "district": "Briar Heights"
  },
  "P38": {
   "name": "The Keene Family Home",
   "district": "Briar Heights"
  },
  "P39": {
   "name": "Ashcombe Conservatory",
   "district": "Briar Heights"
  },
  "P40": {
   "name": "Municipal Hall",
   "district": "Briar Heights"
  },
  "P41": {
   "name": "Winton Court Apartments",
   "district": "Briar Heights"
  },
  "P42": {
   "name": "Hillview Cemetery",
   "district": "Briar Heights"
  },
  "P43": {
   "name": "Willow Court",
   "district": "Southmere"
  },
  "P44": {
   "name": "Community Sports Ground",
   "district": "Southmere"
  },
  "P45": {
   "name": "Southmere Cinema",
   "district": "Southmere"
  },
  "P46": {
   "name": "Southmere Recreation Centre",
   "district": "Southmere"
  },
  "P47": {
   "name": "Canal Walk",
   "district": "Southmere"
  },
  "P48": {
   "name": "Saturday Market",
   "district": "Southmere"
  },
  "P49": {
   "name": "Quarry Lake",
   "district": "North Ridge"
  },
  "P50": {
   "name": "Reservoir Footpath",
   "district": "North Ridge"
  },
  "P51": {
   "name": "Orchard House",
   "district": "North Ridge"
  },
  "P52": {
   "name": "Abandoned Weather Station",
   "district": "North Ridge"
  },
  "P53": {
   "name": "Greyhill Village",
   "district": "North Ridge"
  },
  "P54": {
   "name": "Northwood Rail Crossing",
   "district": "North Ridge"
  },
  "P55": {
   "name": "Bracken Court",
   "district": "The Marches"
  },
  "P56": {
   "name": "Stillwater Docks",
   "district": "The Marches"
  },
  "P57": {
   "name": "The Travelers' House",
   "district": "The Marches"
  },
  "P58": {
   "name": "The Toll Gardens",
   "district": "The Marches"
  },
  "P59": {
   "name": "The Glass Road",
   "district": "The Marches"
  },
  "P60": {
   "name": "Boundary Orchard",
   "district": "The Marches"
  }
 },
 "views": [
  "bracken_court",
  "calder_general",
  "double_shift",
  "iron_footbridge",
  "lyles_bakery",
  "mercy_house",
  "neutral_table",
  "northline_station",
  "okafor_restoration",
  "orchard_house",
  "print_shop",
  "pump_nine",
  "regent",
  "rell_company",
  "rusk_funeral",
  "serrano_yard",
  "sorrell_house",
  "stillwater_docks",
  "switchyard_lane",
  "university"
 ],
 "evidence": {
  "e01": {
   "title": "An interrupted phone recording",
   "text": "Quentin's presence and the sequence; not the murderer's identity.",
   "essential": false
  },
  "e02": {
   "title": "A surviving camera angle",
   "text": "A service vehicle and a worker's movements around the body.",
   "essential": false
  },
  "e03": {
   "title": "Quentin's prepared token",
   "text": "A recognisable kind of protective work, modified.",
   "essential": false
  },
  "e04": {
   "title": "An inconsistent body-handling entry",
   "text": "Someone used an old Mercy House channel and changed the record: Damian's code.",
   "essential": false
  },
  "e05": {
   "title": "A measurable vitality mismatch",
   "text": "Quentin is neither healed nor turned; an external source is involved.",
   "essential": true
  },
  "e06": {
   "title": "Eamon's missed route",
   "text": "A named missing person crossed through a particular threshold.",
   "essential": true
  },
  "e07": {
   "title": "The old rescue report",
   "text": "A similar effect existed, with donor injury, a hard 48-hour limit, and a sensitive who monitored the links.",
   "essential": true
  },
  "e08": {
   "title": "A repair with three contributors",
   "text": "A bond can distribute strain through a prepared cooperative structure.",
   "essential": false
  },
  "e09": {
   "title": "Silas's trial correspondence",
   "text": "Paid recruitment and deception; his death wasn't a miracle.",
   "essential": false
  },
  "e10": {
   "title": "The altered provenance",
   "text": "The old program's frame was sold under a false description.",
   "essential": false
  },
  "e11": {
   "title": "A photographed delivery",
   "text": "A charitable event and a storage movement to Pump Nine overlap.",
   "essential": false
  },
  "e12": {
   "title": "Pump Nine's actual use",
   "text": "A supposedly empty site has occupation, supplies and movement.",
   "essential": false
  },
  "e13": {
   "title": "An authorised route used unofficially",
   "text": "People were carried through a controlled crossing outside its purpose.",
   "essential": false
  },
  "e14": {
   "title": "The donor chambers",
   "text": "The missing men are alive and linked to specific patients.",
   "essential": true
  },
  "e15": {
   "title": "Contradictory promises to Armand",
   "text": "The patron was misled about the hard limit.",
   "essential": false
  },
  "e16": {
   "title": "Damian's control notes",
   "text": "Deliberate prolongation of dependence, manufactured deaths, and the date.",
   "essential": false
  },
  "e17": {
   "title": "A complete distributed plan",
   "text": "A credible alternative with costs and required consent.",
   "essential": false
  },
  "e18": {
   "title": "Institutional responsibility",
   "text": "Who killed, who knowingly enabled, who concealed old harm, who was deceived.",
   "essential": false
  }
 },
 "facts": [
  "know_damian",
  "know_deadline",
  "patients_matched"
 ],
 "calendar": {
  "chapters": [
   {
    "id": "CH01",
    "title": "After the Last Set",
    "from": "2026-08-29",
    "to": "2026-08-30"
   },
   {
    "id": "CH02",
    "title": "The Account I Give",
    "from": "2026-08-30",
    "to": "2026-08-30"
   },
   {
    "id": "CH03",
    "title": "Double Shift",
    "from": "2026-09-01",
    "to": "2026-09-01"
   },
   {
    "id": "CH04",
    "title": "People Who Know",
    "from": "2026-09-01",
    "to": "2026-09-03"
   },
   {
    "id": "CH05",
    "title": "What the Body Keeps",
    "from": "2026-09-04",
    "to": "2026-09-04"
   },
   {
    "id": "CH06",
    "title": "Another Man Missing",
    "from": "2026-09-14",
    "to": "2026-09-19"
   },
   {
    "id": "CH07",
    "title": "An Evening Already Promised",
    "from": "2026-10-02",
    "to": "2026-10-03"
   },
   {
    "id": "CH08",
    "title": "The Second Return",
    "from": "2026-10-15",
    "to": "2026-10-17"
   },
   {
    "id": "CH09",
    "title": "Work Beneath the City",
    "from": "2026-10-29",
    "to": "2026-10-31"
   },
   {
    "id": "CH10",
    "title": "The Closed Program",
    "from": "2026-11-07",
    "to": "2026-11-08"
   },
   {
    "id": "CH11",
    "title": "The Exhibition",
    "from": "2026-11-19",
    "to": "2026-11-20"
   },
   {
    "id": "CH12",
    "title": "Before We Leave",
    "from": "2026-11-24",
    "to": "2026-12-20"
   },
   {
    "id": "CH13",
    "title": "Bracken Court",
    "from": "2026-12-25",
    "to": "2026-12-28"
   },
   {
    "id": "CH14",
    "title": "Passage Denied",
    "from": "2026-12-29",
    "to": "2027-01-01"
   },
   {
    "id": "CH15",
    "title": "Stillwater",
    "from": "2027-01-02",
    "to": "2027-01-03"
   },
   {
    "id": "CH16",
    "title": "The Third Return",
    "from": "2027-01-04",
    "to": "2027-01-09"
   },
   {
    "id": "CH17",
    "title": "What I Ask of Him",
    "from": "2027-01-23",
    "to": "2027-01-31"
   },
   {
    "id": "CH18",
    "title": "A Method We Can Defend",
    "from": "2027-02-01",
    "to": "2027-02-27"
   },
   {
    "id": "CH19",
    "title": "The Offer",
    "from": "2027-03-03",
    "to": "2027-03-06"
   },
   {
    "id": "CH20",
    "title": "Where I Stand",
    "from": "2027-03-13",
    "to": "2027-03-13"
   },
   {
    "id": "CH21",
    "title": "The Links Between Us",
    "from": "2027-03-13",
    "to": "2027-03-14"
   },
   {
    "id": "CH22",
    "title": "The Names We Can Say",
    "from": "2027-03-14",
    "to": "2027-03-21"
   },
   {
    "id": "CH23",
    "title": "Six Weeks Later",
    "from": "2027-04-24",
    "to": "2027-04-24"
   },
   {
    "id": "CH24",
    "title": "One Year Later",
    "from": "2028-03-13",
    "to": "2028-03-13"
   }
  ],
  "parts": [
   {
    "id": "P1",
    "title": "Part One: Late Summer",
    "chapters": [
     "CH01",
     "CH02",
     "CH03",
     "CH04",
     "CH05",
     "CH06",
     "CH07"
    ]
   },
   {
    "id": "P2",
    "title": "Part Two: The Dark Half",
    "chapters": [
     "CH08",
     "CH09",
     "CH10",
     "CH11",
     "CH12"
    ]
   },
   {
    "id": "P3",
    "title": "Part Three: Midwinter",
    "chapters": [
     "CH13",
     "CH14",
     "CH15",
     "CH16",
     "CH17"
    ]
   },
   {
    "id": "P4",
    "title": "Part Four: The Thaw",
    "chapters": [
     "CH18",
     "CH19",
     "CH20",
     "CH21",
     "CH22"
    ]
   },
   {
    "id": "P5",
    "title": "Afterward",
    "chapters": [
     "CH23",
     "CH24"
    ]
   }
  ],
  "fullMoons": [
   "2026-08-28",
   "2026-09-26",
   "2026-10-26",
   "2026-11-24",
   "2026-12-24",
   "2027-01-22",
   "2027-02-20",
   "2027-03-22",
   "2027-04-20"
  ],
  "sunrise": {
   "10": "07:25",
   "11": "07:10",
   "12": "07:50",
   "08": "06:20",
   "09": "06:50",
   "01": "07:50",
   "02": "07:15",
   "03": "06:25",
   "04": "06:20"
  },
  "sunset": {
   "10": "18:05",
   "11": "16:40",
   "12": "16:15",
   "08": "20:00",
   "09": "19:05",
   "01": "16:45",
   "02": "17:35",
   "03": "18:15",
   "04": "19:55"
  }
 },
 "endings": {
  "A": {
   "title": "The Shared Return",
   "core": "All three patients survive and all three donors are freed. The operation closes. A governed recovery program. Institutional wrongdoing addressed explicitly."
  },
  "B": {
   "title": "A City of Witnesses",
   "core": "All six survive; donors freed; communities build their own recovery and accountability. Disclosure chosen separately; never outs a romance."
  },
  "C": {
   "title": "The Long Recovery",
   "core": "Donors freed; all patients survive, with a long recovery, care rotas, lost wages and a timetable. The ring ends."
  },
  "D": {
   "title": "The Private Settlement",
   "core": "Captives freed, patients survive; Damian's operation ends; Armand keeps specified influence and limited protection. A compromise with lasting cost. No new captive replaces an old one."
  },
  "E": {
   "title": "The Severed Bond",
   "core": "Eamon, Hugo and Clive survive and regain autonomy; Quentin, Silas and Felix die. The operation is stopped. Grief, accountability and the donors' perspectives get full scenes. No surviving Quentin romance."
  },
  "F_Q": {
   "title": "What We Could Save: Quentin",
   "core": "All three donors freed. Quentin survives; Silas and Felix die."
  },
  "F_S": {
   "title": "What We Could Save: Silas",
   "core": "All three donors freed. Silas survives; Quentin and Felix die."
  },
  "F_F": {
   "title": "What We Could Save: Felix",
   "core": "All three donors freed. Felix survives; Quentin and Silas die."
  }
 }
};
})(typeof window !== "undefined" ? window : globalThis);
