// Calder: the sixty places, from the bible (§3). base: one of the twenty recurring settings drawn first (§16.3).
"use strict";

const districts = {
  D01: "Old Ward",
  D02: "Eastbank",
  D03: "Foundry Reach",
  D04: "University Hill",
  D05: "Northline",
  D06: "Market Crescent",
  D07: "Briar Heights",
  D08: "Southmere",
  D09: "North Ridge",
  D10: "The Marches",
};

const places = [
  { id: "P01", name: "Mercy House", district: "D01", base: true, notes: "Former hospital, now warden residence, training rooms, infirmary, kitchen, roof, workshop, and archive. People disagree here, recover here, and occasionally have a good evening. C01, C08, C17–C24." },
  { id: "P02", name: "Latch Lane print shop and upstairs home", district: "D01", base: true, notes: "Martin's business, the protagonist's room, Will's clutter, a narrow kitchen, deliveries, visiting relatives, unpaid favors, and customers preparing entirely ordinary events. C09–C10." },
  { id: "P03", name: "Calder Library and public records rooms", district: "D01", base: false, notes: "Study tables, newspaper readers, public computers, historical collections, staff breaks, and incomplete records. Access requires relationships and time rather than breaking in by default. C22, C41." },
  { id: "P04", name: "St. Brendan's Square", district: "D01", base: false, notes: "Steps, food stalls, a church hall, rehearsals, memorial gatherings, school pickups, and a place to wait for someone. Faith and civic life have internal variety. C15, C53." },
  { id: "P05", name: "Old Baths", district: "D01", base: false, notes: "Public swimming pool, changing rooms, staff corridors, reopened upstairs exercise rooms. A place for bodily self-consciousness, friendship, work, and arguments carried from elsewhere. C27, C29." },
  { id: "P06", name: "Riverside Steps", district: "D01", base: false, notes: "Lunch breaks, buskers, dates, anglers, flood marks, and paths under the bridge. The same view can feel different after an absence. C05, C35." },
  { id: "P07", name: "Serrano Yard", district: "D02", base: true, notes: "Workshop below a family home; electrical supplies, repairs, meals, cousins dropping in, and arguments about whose time belongs to whom. C02, C25–C26." },
  { id: "P08", name: "Eastbank Boxing Club", district: "D02", base: false, notes: "Training, youth sessions, older spectators, cleaning, competitions, informal mediation, and a roof needing replacement. C09, C26–C27." },
  { id: "P09", name: "Lyle's Bakery", district: "D02", base: true, notes: "Early shifts, leftovers, customers known by order, and a long table available after closing. C30, C51." },
  { id: "P10", name: "Hartley School and shared playing fields", district: "D02", base: false, notes: "Will's studies and team; community evening classes and weekend use. Young characters have bounded, ordinary lives. C09, C38, C53." },
  { id: "P11", name: "Lock Street Flats", district: "D02", base: false, notes: "Mixed human/werewolf tenants, unreliable heat, noisy neighbors, informal childcare, and a spare room offered with uncomfortable conditions. C28–C29." },
  { id: "P12", name: "Eastbank Allotments", district: "D02", base: false, notes: "Gardens, repairs, borrowed tools, family arguments in public, private conversations while working. Older people come here for reasons beyond dispensing wisdom. C25, C30." },
  { id: "P13", name: "Switchyard", district: "D03", base: true, notes: "Live venue with all-ages shows, paid staff, dressing rooms, loading bay, rehearsal storage, and a contested lease. The rear lane is the opening crime scene. C05, C11, C40, C54." },
  { id: "P14", name: "The Regent", district: "D03", base: true, notes: "Old cinema with converted residential wings. Vampire tenants, human employees, projection booth, communal kitchen, private apartments, and an auditorium still used for films. C04, C31–C36." },
  { id: "P15", name: "Iron Footbridge", district: "D03", base: true, notes: "Public crossing with a concealed, controlled threshold in its maintenance chamber. Leads to P55 when operated by a keeper. C06, C46." },
  { id: "P16", name: "Pump Nine", district: "D03", base: true, notes: "Decommissioned pumping station, machinery hall, inspection passages, offices, roof access, and a disputed property boundary. It becomes important through traceable evidence. C55–C56." },
  { id: "P17", name: "Freight Market", district: "D03", base: false, notes: "Daytime tools, furniture, food, and records; a smaller after-hours trade in difficult objects. Sellers have reputations and customers. C28, C39, C50." },
  { id: "P18", name: "Truss Road Diner", district: "D03", base: false, notes: "Shift workers, venue staff, hospital workers, late buses, awkward mornings, and a booth that is only sometimes free. It belongs to a neighborhood rather than one species. C05, C12, C33." },
  { id: "P19", name: "University arts buildings", district: "D04", base: true, notes: "Studios, deadlines, student disputes, exhibitions, cheap food, visiting families, and competing futures. C03, C41, C52." },
  { id: "P20", name: "Okafor Restoration", district: "D04", base: true, notes: "Front room for clients; workrooms for pigments, wood, and warded objects; family kitchen above. C03, C37–C38, C40." },
  { id: "P21", name: "Bellweather Court", district: "D04", base: false, notes: "Student housing, shared laundry, exams, borrowed chargers, unexpected guests, and leases ending at inconvenient times. C13, C52." },
  { id: "P22", name: "Whitcomb Museum", district: "D04", base: false, notes: "Public galleries, school visits, stores, conservation rooms, evening events, and arguments about loans and ownership. C03, C22, C41." },
  { id: "P23", name: "Calder General", district: "D04", base: true, notes: "An ordinary hospital with a few staff who understand supernatural patients. Waiting rooms, canteen, parking structure, lab, and night shifts all matter. C08, C13, C33, C42." },
  { id: "P24", name: "Observatory Hill Park", district: "D04", base: false, notes: "Public paths below a small teaching observatory; picnics, amateur astronomy, outdoor study, nervous dates, and a place to be quiet together. C03, C13." },
  { id: "P25", name: "Northline Station", district: "D05", base: true, notes: "Regional trains, transfers, lockers, missed departures, temporary work, and encounters with people leaving Calder for real reasons. C05–C07, C49." },
  { id: "P26", name: "Double Shift Café", district: "D05", base: true, notes: "Quentin's work, Peter's management training, familiar commuters, early deliveries, and the protagonist's first sight of the returned victim. C07, C11." },
  { id: "P27", name: "Night Bus Depot", district: "D05", base: false, notes: "Maintenance, rotas, union meetings, packed meals, equipment failures, and people who see the city at different hours. C12, C28." },
  { id: "P28", name: "Laird's Flatshare", district: "D05", base: false, notes: "Three modest bedrooms, arguments about bills, parties that spill into the landing, and a sofa offered with no supernatural motive. C05, C11–C12." },
  { id: "P29", name: "Sable Records", district: "D05", base: false, notes: "Used records, repairs, listening sessions, flyers, and the negotiation of a second chance at performing. C04, C15, C35." },
  { id: "P30", name: "Rusk Funeral Rooms", district: "D05", base: true, notes: "A family business with human services, storage, private grief, and carefully limited supernatural work. Its owner and his family disagree about those obligations. C19, C43." },
  { id: "P31", name: "Rell & Company", district: "D06", base: true, notes: "Antiques, salvage, appraisals, a cluttered workroom, wealthy clients, and objects whose provenance has been edited. C39–C40, C44." },
  { id: "P32", name: "Crescent Market", district: "D06", base: false, notes: "Groceries, cooked food, flowers, competition between stalls, errands, chance meetings, and a public place where someone can refuse a private conversation. C10, C30." },
  { id: "P33", name: "Little Glass Arcade", district: "D06", base: false, notes: "Small businesses sharing a covered passage, empty units, a locksmith, parcels, and a café table borrowed by informal traders. C46, C50." },
  { id: "P34", name: "The Lantern Rooms", district: "D06", base: false, notes: "Low-cost rehearsal and teaching spaces. Lessons, bad auditions, instrument repairs, arguments over bookings, and an uncertain grant. C15, C40, C53." },
  { id: "P35", name: "The Neutral Table", district: "D06", base: true, notes: "A restaurant whose owner rents an upstairs room for meetings between supernatural representatives. Hospitality does not compel honesty or peace. C18, C25, C31, C45." },
  { id: "P36", name: "Calder Tenants' Advice Centre", district: "D06", base: false, notes: "Appointments, cramped files, waiting, small victories, legal advocacy, and the human consequences of a property sale. C14, C34, C55." },
  { id: "P37", name: "Sorrell House", district: "D07", base: true, notes: "A beautiful inhabited house with a diminished household, charity events, locked family rooms, and staff who know which questions are unwelcome. C39, C44, C56." },
  { id: "P38", name: "The Keene Family Home", district: "D07", base: false, notes: "Family meals, trophies, neglected rooms, repair work, and the old habits Adrian resumes before noticing. C01, C17–C18." },
  { id: "P39", name: "Ashcombe Conservatory", district: "D07", base: false, notes: "Hired events, public garden hours, exhibitions, fundraisers, contractors, and polished conversations with material stakes. C03, C44, C55." },
  { id: "P40", name: "Municipal Hall", district: "D07", base: false, notes: "Public meetings, licensing arguments, election work, civil servants, and people waiting to be heard. Supernatural influence is partial and contested. C16, C34, C55." },
  { id: "P41", name: "Winton Court Apartments", district: "D07", base: false, notes: "Older prosperous tenants, service corridors, Russell's modest apartment, repairs, and quiet conflicts over redevelopment. C14, C34, C44." },
  { id: "P42", name: "Hillview Cemetery", district: "D07", base: false, notes: "Funerals, maintenance, family visits, disputed memorials, and old burial records. Many graves have no supernatural secret. C19, C43, C53." },
  { id: "P43", name: "Willow Court", district: "D08", base: false, notes: "Ordinary apartment blocks, balconies, deliveries, washing, a residents' group, and a service that never quite arrives. C12, C16." },
  { id: "P44", name: "Community Sports Ground", district: "D08", base: false, notes: "Will's matches, Tomas's coaching, arguments over access, spectators, and inconvenient rain. C09, C27, C38." },
  { id: "P45", name: "Southmere Cinema", district: "D08", base: false, notes: "Cheap late screenings, part-time employment, disappointing snacks, crowded buses home, and an alternative to supernatural nightlife. C05, C35." },
  { id: "P46", name: "Southmere Recreation Centre", district: "D08", base: false, notes: "Benoît's classes, private bookings, a struggling youth program, and Malcolm teaching practical skills. C15, C24, C53." },
  { id: "P47", name: "Canal Walk", district: "D08", base: false, notes: "Towpaths, footbridges, anglers, utility works, commuting shortcuts, and a partly overgrown stretch used by smugglers. C16, C49, C55." },
  { id: "P48", name: "Saturday Market", district: "D08", base: false, notes: "Work clothes, produce, household objects, neighborhood gossip, gifts bought with limited money, and the occasional fair. C10, C30." },
  { id: "P49", name: "Quarry Lake", district: "D09", base: false, notes: "Day trips, a closed worksite, swimming in permitted areas, an old access road, and a place friends already know. C02, C05, C27." },
  { id: "P50", name: "Reservoir Footpath", district: "D09", base: false, notes: "Maintenance access, public walks, birdwatchers, running, and a route that can be followed without magical expertise. C08, C24." },
  { id: "P51", name: "Orchard House", district: "D09", base: true, notes: "A modest warden recovery retreat. Garden, kitchen, guest rooms, workshop, a dog, and a sealed crossing to P60 under custodial control. C08, C24, C48." },
  { id: "P52", name: "Abandoned Weather Station", district: "D09", base: false, notes: "Obsolete equipment and a decommissioned watch post. Old reports explain specific boundary disturbances. C21–C22, C24." },
  { id: "P53", name: "Greyhill Village", district: "D09", base: false, notes: "Regional bus stop, general store, inn, houses, and residents with their own knowledge of nearby land. C24, C28, C48." },
  { id: "P54", name: "Northwood Rail Crossing", district: "D09", base: false, notes: "A fixed, dangerous threshold to P59. Its earthly approach is on a disused rail spur; authorization and route knowledge matter. C06, C46, C49." },
  { id: "P55", name: "Bracken Court", district: "D10", base: true, notes: "An inhabited market town reached from Iron Footbridge. Houses, an inn, family workshops, official rooms, and people irritated by visitors. C06, C45, C47, C50." },
  { id: "P56", name: "Stillwater Docks", district: "D10", base: true, notes: "Working docks and old rented warehouses. Deliveries, boat repairs, crews, and a concealed holding site connected to the return operation. C49–C50, C56." },
  { id: "P57", name: "The Travelers' House", district: "D10", base: false, notes: "Lodging with shared meals, crowded corridors, local rules, debts of hospitality, and guests who will depart whether the protagonist is ready or not. C06, C47–C48." },
  { id: "P58", name: "The Toll Gardens", district: "D10", base: false, notes: "Public gardens around a court and crossing office; celebrations, hearings, family meetings, and private political bargains. C45, C47, C50." },
  { id: "P59", name: "The Glass Road", district: "D10", base: false, notes: "An old road through unsettled border country reached from Northwood. Reflections make certain concealed bindings visible, but cannot supply names, motives, or history. C06, C46, C48." },
  { id: "P60", name: "Boundary Orchard", district: "D10", base: false, notes: "Cultivated land around the third crossing, with sheds, seasonal workers, paths, and conflicting claims over its use. Its Calder exit is P51. C24, C45, C48." },
];

module.exports = { districts, places };
