#!/usr/bin/env node
// Generates js/story/plan-data.js from plan/ so the game and the checked plan share one source of truth:
// variables (with defaults and clamps), people, places, evidence, the calendar, and dated status changes.
//   node tools/gen-config.js
"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const P = (f) => require(path.join(ROOT, "plan", f));
const { vars, LEADS } = P("state.js");
const { cast } = P("cast.js");
const { places, districts } = P("places.js");
const { evidence, facts } = P("evidence.js");
const cal = P("calendar.js");
const { endings } = P("endings.js");

const slug = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
const OVERRIDE = { MC: "mc", C18: "orrell" };
const people = {};
for (const c of cast) {
  const id = OVERRIDE[c.id] || slug(c.name.split(" ")[0]);
  if (people[id]) throw new Error("duplicate person id " + id);
  people[id] = { cid: c.id, name: c.name.replace(/ \(.*\)$/, ""), age: c.age, kind: c.kind, tier: c.tier, romance: !!c.romance,
    appearance: c.appearance || "", status: c.status || [], home: c.home || "" };
}

const startVars = {}, clamp = {};
for (const [k, d] of Object.entries(vars)) {
  startVars[k] = d.default;
  if (d.type !== "number") continue;
  if (/^st_/.test(k)) clamp[k] = [0, 6];
  else if (/^fr_/.test(k)) clamp[k] = [0, 3];
  else if (/^hurt_/.test(k)) clamp[k] = [0, 2];
  else if (["nerve", "craft", "people", "knack"].includes(k)) clamp[k] = [0, 100];
  else if (k === "strain") clamp[k] = [0, 3];
}

// route beats (plan/routes.js) are flags too
const { routes } = P("routes.js");
for (const r of routes) for (const b of r.beats) if (!(b.flag in startVars)) startVars[b.flag] = false;

const views = fs.readdirSync(path.join(ROOT, "art/places")).filter((f) => f.endsWith(".png")).map((f) => f.replace(/\.png$/, "").replace(/-/g, "_"));

const data = {
  startVars, clamp, leads: LEADS, people,
  places: Object.fromEntries(places.map((p) => [p.id, { name: p.name, district: districts[p.district] }])),
  views,
  evidence: Object.fromEntries(evidence.map((e) => [e.id, { title: e.name, text: e.establishes, essential: e.essential }])),
  facts,
  calendar: { chapters: cal.chapters.map((c) => ({ id: c.id, title: c.title, from: c.from, to: c.to })), parts: cal.parts, fullMoons: cal.fullMoons, sunrise: cal.sunrise, sunset: cal.sunset },
  endings: Object.fromEntries(endings.map((e) => [e.id, { title: e.name, core: e.core }]))
};

const out = "/* Calder — generated by tools/gen-config.js from plan/. Do not edit by hand. */\n" +
  "(function (root) {\n  \"use strict\";\n  var NB = root.NB || (root.NB = {});\n  NB.plan = " + JSON.stringify(data, null, 1) + ";\n})(typeof window !== \"undefined\" ? window : globalThis);\n";
fs.mkdirSync(path.join(ROOT, "js/story"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "js/story/plan-data.js"), out);
console.log(`wrote js/story/plan-data.js: ${Object.keys(startVars).length} variables, ${Object.keys(people).length} people, ${places.length} places, ${views.length} views, ${evidence.length} clues`);
