#!/usr/bin/env node
// Lists the art on disk into js/art/asset-files.js (paths relative to index.html). tools/build.js inlines them.
//   art/places/<view>.png                 -> places[view]
//   art/cards/<id>.png                    -> cards[id]         (chapter and ending cards)
//   art/portraits/cNN-<name>-<mood>.png   -> portraits["<name>:<mood>"]   (ChatGPT's files)
//   art/snapshots/snap-NN-<slot>[-var].png -> snapshots["<slot>[-var]"]
"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const list = (d) => (fs.existsSync(path.join(ROOT, d)) ? fs.readdirSync(path.join(ROOT, d)).filter((f) => f.endsWith(".png")).sort() : []);
const out = { places: {}, cards: {}, portraits: {}, snapshots: {} };
for (const f of list("art/places")) out.places[f.slice(0, -4).replace(/-/g, "_")] = "art/places/" + f;
for (const f of list("art/cards")) out.cards[f.slice(0, -4).replace(/-/g, "_")] = "art/cards/" + f;
for (const f of list("art/portraits")) {
  // cNN-name-mood.png, cNN-name-variant-mood.png, or cNN-name-variant.png (lower case; hyphens or underscores)
  const m = /^c\d\d[-_]([a-z]+)[-_](.+)\.png$/i.exec(f) || /^(mc)[-_](.+)\.png$/i.exec(f);
  if (m) out.portraits[m[1].toLowerCase() + ":" + m[2].toLowerCase().replace(/_/g, "-")] = "art/portraits/" + f;
}
for (const f of list("art/snapshots")) { const m = /^snap-\d\d-(.+)\.png$/.exec(f); if (m) out.snapshots[m[1]] = "art/snapshots/" + f; }
fs.writeFileSync(path.join(ROOT, "js/art/asset-files.js"), "/* Generated by tools/gen-assets.js. */\n(function (root) { (root.NB || (root.NB = {})).ASSET_FILES = " + JSON.stringify(out, null, 1) + "; })(typeof window !== \"undefined\" ? window : globalThis);\n");
console.log(`wrote js/art/asset-files.js: ${Object.keys(out.places).length} places, ${Object.keys(out.cards).length} cards, ${Object.keys(out.portraits).length} portraits, ${Object.keys(out.snapshots).length} snapshots`);
